class AppRouterName {
  AppRouterName._();
  static const String splash = 'splash';
  static const String home = 'home';
  static const String onBoarding = 'on_boarding';
  static const String auth = 'auth';
  static const String login = 'login';
  static const String forgotPassword = 'forgot_password';
  static const String signup = 'signup';
  static const String favourite = 'favourite';
  static const String user = 'user';
  static const String payment = 'payment';
  static const String booking = 'booking';
  static const String hotel = 'hotel';
  static const String flights = 'flights';
  static const String all = 'all';
  static const String detail = 'detail';
  static const String room = 'room';
  static const String filter = 'filter';
  static const String checkoutHotel = 'checkout_hotel';
  static const String contactHotel = 'contact_hotel';
  static const String promoHotel = 'promo_hotel';
  static const String addCardHotel = 'add_card_hotel';
  static const String bookFlight = 'book_flight';
  static const String resultFlight = 'result_flight';
  static const String sortBy = 'sort_by';
  static const String facilities = 'facilities';
  static const String selectSeat = 'select_seat';
  static const String checkoutFlight = 'checkout_flight';
  static const String contactFlight = 'contact_flight';
  static const String promoFlight = 'promo_flight';
  static const String addCardFlight = 'add_card_flight';
  static const String addPassengerFlight = 'add_passenger_flight';
  static const String reviewHotel = 'review_hotel';
  static const String addReviewHotel = 'add_review_hotel';
  static const String editReviewHotel = 'edit_review_hotel';
}
